 # Version2.1 of gitlab ci

stages:
  - stress-test-dev
  - stress-test-acc
  - build
  - package
  - deploy-to-dev
  - deploy-to-test
  - deploy-to-acc
  - deploy-to-prod

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"
  APP_NAME: routeplanner
  APP_VERSION: v1
  NAMESPACE: ${APP_NAME}
  DEPLOYMENT: ${APP_NAME}
  ING_PATH: ${APP_VERSION}/${APP_NAME}

cache:
  paths:
    - .m2/repository

java-unit-tests:
  stage: build
  image: maven:3.6.0-jdk-8-alpine
  script:
    - mvn $MAVEN_CLI_OPTS clean package -B
    - cat target/site/jacoco-ut/index.html
  artifacts:
    paths:
    - target/site/jacoco-ut/
    reports:
      junit: target/surefire-reports/TEST-*.xml
  coverage: '/Total.*?([0-9]{1,3})%/'
  tags:
    - k8s-dev

java-integration-tests:
  stage: build
  image: 593241407630.dkr.ecr.eu-central-1.amazonaws.com/stress-test:88cb2a7f
  script:
    - mvn $MAVEN_CLI_OPTS clean test-compile failsafe:integration-test failsafe:verify -B
  tags:
    - k8s-dev

build-container:
  stage: package
  image: docker:17
  variables:
    DOCKER_API_VERSION: "1.23"
  script:
  - pwd
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - docker build -t ${PROD_REPO_URL}/${APP_NAME}:${CI_COMMIT_SHA:0:8} .
  - export AWS_ACCESS_KEY_ID=${PROD_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${PROD_SECRET_ACCESS_KEY}
  - $(aws ecr get-login --no-include-email --region eu-central-1)
  - docker push ${PROD_REPO_URL}/${APP_NAME}:${CI_COMMIT_SHA:0:8}
  only:
  - master
  tags:
  - k8s-dev

build-branch-container:
  stage: package
  image: docker:17
  variables:
    DOCKER_API_VERSION: "1.23"
  script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - docker build -t ${PROD_REPO_URL}/${APP_NAME}:${CI_COMMIT_SHA:0:8} .
    - export AWS_ACCESS_KEY_ID=${PROD_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${PROD_SECRET_ACCESS_KEY}
    - $(aws ecr get-login --no-include-email --region eu-central-1)
    - docker push ${PROD_REPO_URL}/${APP_NAME}:${CI_COMMIT_SHA:0:8}
  except:
    - master
  allow_failure: false
  when: manual
  tags:
    - k8s-dev

.deploy: &deploy_template
  image: lachlanevenson/k8s-kubectl:v1.10.4
  script:
    - sed -i -e "s#{CONTAINER_IMAGE}#${PROD_REPO_URL}/${APP_NAME}:${CI_COMMIT_SHA:0:8}#g" -e "s/{APP_NAME}/${APP_NAME}/g" -e "s/{NAMESPACE}/${NAMESPACE}/g" k8s/deployment.yml
    - kubectl apply -f k8s/deployment.yml
    - sed -i -e "s/{APP_NAME}/${APP_NAME}/g" -e "s/{NAMESPACE}/${NAMESPACE}/g" -e "s#{ING_PATH}#${ING_PATH}#g" -e "s/{FQDN}/${FQDN}/g" k8s/svc_ing.yml
    - kubectl apply -f k8s/svc_ing.yml
    - sed -i -e "s/{APP_NAME}/${APP_NAME}/g" -e "s/{NAMESPACE}/${NAMESPACE}/g" -e "s/{MINREP}/${MINREP}/g" -e "s/{MAXREP}/${MAXREP}/g" k8s/hpa.yml
    - kubectl apply -f k8s/hpa.yml
    - kubectl -n ${NAMESPACE} rollout status deployment ${DEPLOYMENT}

deploy-dev:
  <<: *deploy_template
  stage: deploy-to-dev
  variables:
    MINREP: 2
    MAXREP: 10
    FQDN: internal.dev.cloud.jumbo.com
  tags:
    - k8s-dev

deploy-test:
  <<: *deploy_template
  stage: deploy-to-test
  variables:
    MINREP: 2
    MAXREP: 10
    FQDN: internal.test.cloud.jumbo.com
  only:
  - master
  tags:
   - k8s-test
  when: manual

deploy-acc:
  <<: *deploy_template
  stage: deploy-to-acc
  variables:
    MINREP: 2
    MAXREP: 10
    FQDN: internal.acc.cloud.jumbo.com
  only:
  - master
  tags:
   - k8s-acc
  when: manual

deploy-prod:
  <<: *deploy_template
  stage: deploy-to-prod
  variables:
    MINREP: 4
    MAXREP: 16
    FQDN: internal.prod.cloud.jumbo.com
  only:
    - master
  tags:
    - k8s-prod
  when: manual

stress-tests-route-dev:
  stage: stress-test-dev
  image: 593241407630.dkr.ecr.eu-central-1.amazonaws.com/stress-test:88cb2a7f
  script:
    - export MAVEN_OPTS="-Xms128m -Xmx256m -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    - mvn gatling:test -Dgatling.simulationClass=com.jumbo.simulation.RouteSimulation -Denvironment=DEV -B
  when: manual
  tags:
    - k8s-dev
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - target/
    expire_in: 1 week

stress-tests-postalcode-dev:
  stage: stress-test-dev
  image: 593241407630.dkr.ecr.eu-central-1.amazonaws.com/stress-test:88cb2a7f
  script:
    - export MAVEN_OPTS="-Xms128m -Xmx256m -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    - mvn gatling:test -Dgatling.simulationClass=com.jumbo.simulation.PostalCodeSimulation -Denvironment=DEV -B
  when: manual
  tags:
    - k8s-dev
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - target/
    expire_in: 1 week

stress-tests-route-acc:
  stage: stress-test-acc
  image: 593241407630.dkr.ecr.eu-central-1.amazonaws.com/stress-test:88cb2a7f
  script:
    - export MAVEN_OPTS="-Xms128m -Xmx256m -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    - mvn gatling:test -Dgatling.simulationClass=com.jumbo.simulation.RouteSimulation -Denvironment=ACC -B
  when: manual
  tags:
    - k8s-acc
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - target/
    expire_in: 1 week

stress-tests-postalcode-acc:
  stage: stress-test-acc
  image: 593241407630.dkr.ecr.eu-central-1.amazonaws.com/stress-test:88cb2a7f
  script:
    - export MAVEN_OPTS="-Xms128m -Xmx256m -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    - mvn gatling:test -Dgatling.simulationClass=com.jumbo.simulation.PostalCodeSimulation -Denvironment=ACC -B
  when: manual
  tags:
    - k8s-acc
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - target/
    expire_in: 1 week